<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"会议管理",
                        "menuJump":"列表",
                        "tableName":"huiyi"
                    }
					,{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"会议文件管理",
                        "menuJump":"列表",
                        "tableName":"huiyiwenjian"
                    }
                ],
                "menu":"会议管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"任务管理",
                        "menuJump":"列表",
                        "tableName":"renwuOne"
                    }
                ],
                "menu":"任务管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"系统公告管理",
                        "menuJump":"列表",
                        "tableName":"xitonggonggao"
                    }
                ],
                "menu":"系统公告管理"
            }
			,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"会议室管理",
                        "menuJump":"列表",
                        "tableName":"dictionary"
                    }
                ],
                "menu":"会议室管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,{
        "backMenu":[
			{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除"
                        ],
                        "menu":"会议管理",
                        "menuJump":"列表",
                        "tableName":"huiyi"
                    }
					,{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"会议文件管理",
                        "menuJump":"列表",
                        "tableName":"huiyiwenjian"
                    }
                ],
                "menu":"会议管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除"
                        ],
                        "menu":"任务管理",
                        "menuJump":"列表",
                        "tableName":"renwuOne"
                    }
                ],
                "menu":"任务管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"系统公告管理",
                        "menuJump":"列表",
                        "tableName":"xitonggonggao"
                    }
                ],
                "menu":"系统公告管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"经理",
        "tableName":"yonghu"
    }
	,{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"会议管理",
                        "menuJump":"列表",
                        "tableName":"huiyi"
                    }
					,{
                        "buttons":[
                        ],
                        "menu":"会议文件管理",
                        "menuJump":"列表",
                        "tableName":"huiyiwenjian"
                    }
                ],
                "menu":"会议管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"任务管理",
                        "menuJump":"列表",
                        "tableName":"renwuOne"
                    }
                ],
                "menu":"任务管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                        ],
                        "menu":"系统公告管理",
                        "menuJump":"列表",
                        "tableName":"xitonggonggao"
                    }
                ],
                "menu":"系统公告管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"用户",
        "tableName":"yonghu"
    }
];

var hasMessage = '';
